export const GET_COMMENTS_REQUEST ='GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS ='GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL ='GET_COMMENTS_FAIL';



export const ADD_COMMENT ='ADD_COMMENT';
export const DELETE_COMMENT ='DELETE_COMMENT';
export const UPDATE_COMMENT ='UPDATE_COMMENT';


