


export const GET_CONVERSATIONS_REQUEST  ='GET_CONVERSATIONS_REQUEST';
export const GET_CONVERSATIONS_SUCCESS  ='GET_CONVERSATIONS_SUCCESS';

export const ADD_CONVERSATION  ='ADD_CONVERSATION';




