export const GET_FRIENDS_REQUEST_REQUEST ='GET_FRIENDS_REQUEST_REQUEST';
export const GET_FRIENDS_REQUEST_SUCCESS='GET_FRIENDS_REQUEST_SUCCESS';
export const GET_FRIENDS_REQUEST_FAIL ='GET_FRIENDS_REQUEST_FAIL';



export const ADD_FRIEND_REQUEST  ='ADD_FRIEND_REQUEST';
export const DELETE_FRIEND_REQUEST  ='DELETE_FRIEND_REQUEST';
export const RECEIVER_FRIEND_REQUEST  ='RECEIVER_FRIEND_REQUEST';




