export const GET_USER_FRIENDS_REQUEST ='GET_USER_FRIENDS_REQUEST';
export const GET_USER_FRIENDS_SUCCESS='GET_USER_FRIENDS_SUCCESS';
export const GET_USER_FRIENDS_FAIL ='GET_USER_FRIENDS_FAIL';

export const ADD_USER_FRIEND ='ADD_USER_FRIEND';

export const GET_USER_OTHERS_REQUEST ='GET_USER_OTHERS_REQUEST';
export const GET_USER_OTHERS_SUCCESS='GET_USER_OTHERS_SUCCESS';
export const GET_USER_OTHERS_FAIL ='GET_USER_OTHERS_FAIL';
export const DELETE_USER_OTHER ='DELETE_USER_OTHER';



