export const GET_POSTS_REQUEST ='GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS ='GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL ='GET_POSTS_FAIL';



export const ADD_POST ='ADD_POST';
export const DELETE_POST ='DELETE_POST';


