export const GET_USER_FRIENDS_REQUEST ='GET_USER_FRIENDS_REQUEST';
export const GET_USER_FRIENDS_SUCCESS='GET_USER_FRIENDS_SUCCESS';
export const GET_USER_FRIENDS_FAIL ='GET_USER_FRIENDS_FAIL';

export const ADD_USER_FRIEND ='ADD_USER_FRIEND';

export const GET_USER_OTHERS_REQUEST ='GET_USER_OTHERS_REQUEST';
export const GET_USER_OTHERS_SUCCESS='GET_USER_OTHERS_SUCCESS';
export const GET_USER_OTHERS_FAIL ='GET_USER_OTHERS_FAIL';

export const GET_USER_PROFILE_REQUEST ='GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS='GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL ='GET_USER_PROFILE_FAIL';


export const UPDATE_USER_PROFILE ='UPDATE_USER_PROFILE';


export const GET_USERS = "GET_USERS";


